admin/src/web/utils/forms/service.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SelectField, StringField
from wtforms.validators import DataRequired, Length, Regexp

from src.web.utils.forms.choices import service_lab_choices


class ServiceCreateForm(FlaskForm):
    name = StringField("Nombre", validators=[DataRequired("Campo requerido")])
    description = StringField(
        "Descripción", validators=[DataRequired("Campo requerido")]
    )
    keywords = StringField(
        "Palabras clave",
        validators=[
            DataRequired("Campo requerido"),
            Length(max=100, message="Máximo 100 caracteres"),
            Regexp(
                r"^([a-zA-Z0-9]+)(,\s*[a-zA-Z0-9]+)*$",
                message="Solo letras y números separados por coma",
            ),
        ],
    )
    service_type = StringField(
        "Tipo de Servicio", validators=[DataRequired("Campo requerido")]
    )
    service_type = SelectField("Tipo de servicio", choices=service_lab_choices)


class ServiceUpdateForm(ServiceCreateForm):
    enabled = BooleanField("Habilitado", validators=[DataRequired("Campo requerido")])

admin/src/web/controllers/service.py
"""Service routing logic"""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from werkzeug import exceptions

from src.dbo import configuration_dbo, service_dbo
from src.models.enums import Operations, ServiceTypes
from src.web.utils import model as model_utils
from src.web.utils import session as session_utils
from src.web.utils.auth import validate_operation
from src.web.utils.forms.crud import ConfirmDeleteForm
from src.web.utils.forms.service import ServiceCreateForm, ServiceUpdateForm

service_routing = Blueprint(
    "services",
    __name__,
    static_folder="static",
    template_folder="templates/services",
    url_prefix="/services",
)


@service_routing.get("/")
@validate_operation(operation=Operations.SERVICE.index)
def service_index():
    """Returns all services and renders the services page"""
    query = request.args.get("q", default="")
    service_type = request.args.get("type", default="", type=ServiceTypes)
    page = request.args.get("page", default=1, type=int)
    per_page = configuration_dbo.get_per_page()
    inst_id = session_utils.get_inst_id()
    services, total_pages = service_dbo.search_by_institution(
        inst_id, query, service_type, page, per_page
    )

    return render_template(
        "services/service-index.html",
        delete_form=ConfirmDeleteForm(),
        services=services,
        page=page,
        total_pages=total_pages,
    )


@service_routing.get("/<service_id>")
@validate_operation(operation=Operations.SERVICE.show)
def service_show(service_id):
    """
    Returns the service page
    :param service_id: service id
    """
    service = service_dbo.get_by_id(service_id)
    serialized = model_utils.enum_mutation(service.serialize(), lambda x: x.name)
    serialized["keywords"] = ",".join(serialized["keywords"])
    form = ServiceUpdateForm(data=serialized)
    return render_template("services/service-update.html", service=service, form=form)


@service_routing.post("/<service_id>/update")
@validate_operation(Operations.SERVICE.update)
def service_update(service_id):
    """
    Updates a service
    :param service_id: service id
    """
    current = service_dbo.get_by_id(service_id)
    form = ServiceUpdateForm(request.form)
    if form.validate():
        keywords = form.data["keywords"].split(",")
        keywords = [keyword.strip() for keyword in keywords]
        service_dbo.update(service=current, data={**form.data, "keywords": keywords})
        flash("Servicio actualizado exitosamente!", "success")
        return redirect(url_for("services.service_index"))
    else:
        flash("Error al actualizar el servicio", "error")
        return render_template(
            "services/service-update.html", service=current, form=form
        )


@service_routing.route("/create", methods=["GET", "POST"])
@validate_operation(Operations.SERVICE.create)
def service_create():
    """Creates a new service"""
    form = ServiceCreateForm(request.form)
    if request.method == "GET":
        form = ServiceCreateForm()
        return render_template("services/service-create.html", form=form)
    # post
    if not form.validate():
        flash("Error al crear el servicio", "error")
        return render_template("services/service-create.html", form=form)
    new_service = form.data
    new_service.pop("csrf_token")
    keywords = form.data["keywords"].split(",")
    new_service["keywords"] = [keyword.strip() for keyword in keywords]
    try:
        service_dbo.create_new(**new_service, inst_id=session_utils.get_inst_id())
        flash("Servicio añadido exitosamente!", "success")
    except exceptions.HTTPException as e:
        flash(e.description, "error")
        return render_template("services/service-create.html", form=form)
    return redirect(url_for("services.service_index"))


@service_routing.post("/<service_id>/delete")
@validate_operation(Operations.SERVICE.delete)
def service_delete(service_id):
    """
    Deletes a service
    :param service_id: service id
    """
    current = service_dbo.get_by_id(service_id)
    service_dbo.delete(current)
    flash("Servicio eliminado exitosamente!", "success")
    return redirect(url_for("services.service_index"))

admin/src/web/templates/services/service-create.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h1 class="text-2xl text-white mb-4">Crear Servicio</h1>
    <section class="mb-12 ">
        {% call Form.render_form(form, method="POST", action=url_for('services.service_create')) %}
        {{ Form.button_submit("Crear") }}
        {% endcall %}
    </section>
{% endblock %}

admin/src/web/templates/services/service-index.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% import "_components/pagination.html" as Pagination %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <hgroup class="flex items-center justify-between">
        <h1 class="text-2xl text-white mb-4">Administracion de servicios</h1>
        <a href="{{ url_for('services.service_create') }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4
        focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2
        dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Añadir</a>

    </hgroup>

    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nombre
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Descripción
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Laboratorio
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Tipo
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Habilitado
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for service in services %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ service.name }}
                    </th>
                    <td class="px-6 py-4">
                        {{ service.description }}
                    </td>
                    <td class="px-6 py-4">
                        {{ service.laboratory }}
                    </td>
                    <td class="px-6 py-4">
                        {{ service.service_type }}
                    </td>
                    <td class="px-6 py-4">
                        {% if service.enabled %}
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                        Si</span>
                        {% else %}
                        <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100">
                        No</span>
                        {% endif %}
                    </td>
                    <td class="px-3 py-4 flex flex-col gap-1">
                        <a href="{{ url_for('services.service_show', service_id=service.id) }}" type="submit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Editar</a>
                        {% if session["role"] != "OPERATOR" %}
                        {% call Form.render_form(delete_form, method="POST", action=url_for('services.service_delete', service_id=service.id), class='flex') %}
                        {{ Form.button_submit("Eliminar", class="font-medium text-red-600 dark:text-red-500 hover:underline") }}
                        {% endcall %}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% if services|length == 0 %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th colspan="7" scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        No se encontraron resultados
                    </th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <br/>
    {{ Pagination.render_pagination(url_for('services.service_index'), page, total_pages) }}

</section>
</div>
{% endblock %}

admin/src/web/templates/services/service-show.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h1 class="text-2xl text-white mb-4">Añadir Servicio</h1>
    <section class="mb-12 ">
        {% call Form.render_form(form, method="POST", action=url_for('services.service_add')) %}
        {{ Form.button_submit("Añadir") }}
        {% endcall %}
    </section>
{% endblock %}

admin/src/web/templates/services/service-update.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h1 class="text-2xl text-white mb-4">Actualizar Servicio</h1>
    <section class="mb-12">
        {% call Form.render_form(form, method="POST", action=url_for('services.service_update', service_id=service.id)) %}
        {{ Form.button_submit("Actualizar") }}
        {% endcall %}
    </section>
{% endblock %}