admin/src/web/utils/forms/service_request.py
from flask_wtf import FlaskForm
from wtforms import DateField, SelectField, StringField, TextAreaField
from wtforms.validators import DataRequired

from src.models.enums import ServiceRequestStatus
from src.web.utils.forms.choices import service_lab_choices

request_choices = [(status.name, status.value) for status in ServiceRequestStatus]


class ServiceRequestSearchForm(FlaskForm):
    user_id = SelectField("Usuario")
    service_type = SelectField(
        "Tipo de servicio", choices=[("", "Todos"), *service_lab_choices]
    )
    status = SelectField("Estado", choices=[("", "Todos"), *request_choices])
    creation_date_start = DateField("Fecha de creación desde")
    creation_date_end = DateField("Fecha de creación hasta")


class ServiceRequestCreateForm(FlaskForm):
    title = StringField("Título", validators=[DataRequired("Campo requerido")])
    description = TextAreaField(
        "Descripción", validators=[DataRequired("Campo requerido")]
    )
    status = SelectField(
        "Estado", choices=request_choices, validators=[DataRequired("Campo requerido")]
    )
    service_id = StringField("Servicio", validators=[DataRequired("Campo requerido")])


class ServiceRequestUpdateForm(FlaskForm):
    status = SelectField(
        "Estado", choices=request_choices, validators=[DataRequired("Campo requerido")]
    )


class ServiceRequestNoteForm(FlaskForm):
    note = TextAreaField("Comentario", validators=[DataRequired("Campo requerido")])

admin/src/web/controllers/service_request.py
from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, request, url_for

from src.dbo import service_request_dbo, user_dbo
from src.models.enums import Operations
from src.web.utils import session as session_utils
from src.web.utils.auth import validate_operation
from src.web.utils.forms.service_request import (
    ServiceRequestCreateForm,
    ServiceRequestNoteForm,
    ServiceRequestSearchForm,
    ServiceRequestUpdateForm,
)

service_request_routing = Blueprint(
    "service_request",
    __name__,
    static_folder="static",
    template_folder="templates/service_requests",
)


@service_request_routing.get("/service_requests")
@validate_operation(Operations.SERVICE_REQUEST.index)
def service_request_index():
    """Returns all service_requests and renders the service_request page"""
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", 1, type=int)
    search_form = ServiceRequestSearchForm(
        user_id=request.args.get("user_id", None),
        creation_date_start=request.args.get(
            "creation_date_start", None, type=datetime.fromisoformat
        ),
        creation_date_end=request.args.get(
            "creation_date_end", None, type=datetime.fromisoformat
        ),
        service_type=request.args.get("service_type", None),
        status=request.args.get("status", None),
    )
    users = [
        (user.id, user.username)
        for user in user_dbo.list_by_institution(session_utils.get_inst_id())
    ]
    search_form.user_id.choices = [("", "Todos"), *users]

    form_data = search_form.data
    form_data.pop("csrf_token")
    service_requests, total_pages = service_request_dbo.search_by_user(
        **form_data,
        inst_id=session_utils.get_inst_id(),
        page=page,
        per_page=per_page,
    )
    return render_template(
        "service_requests/service_request-index.html",
        page=page,
        total_pages=total_pages,
        service_requests=service_requests,
        search_form=search_form,
    )


@service_request_routing.get("/service_requests/<req_id>")
@validate_operation(Operations.SERVICE_REQUEST.show)
def service_request_show(req_id):
    """Return the service_request page"""
    service_request = service_request_dbo.get_realted_by_id(req_id)
    notes = service_request_dbo.get_notes_by_req(req_id)

    return render_template(
        "service_requests/service_request-show.html",
        service_request=service_request,
        notes=notes,
    )


@service_request_routing.route(
    "/service_requests/<req_id>/update", methods=["GET", "POST"]
)
@validate_operation(Operations.SERVICE_REQUEST.update)
def service_request_update(req_id):
    """Updates the service_request"""

    update_form = ServiceRequestUpdateForm(request.form)
    note_form = ServiceRequestNoteForm()
    service_request = service_request_dbo.get_related_by_id(req_id)

    if service_request is None:
        flash("Error al encontrar el pedido", "error")
        return redirect(url_for("service_request.service_request_index"))

    if request.method == "GET":
        update_form = ServiceRequestUpdateForm(status=service_request["status"].name)
        return render_template(
            "service_requests/service_request-update.html",
            service_request=service_request,
            update_form=update_form,
            note_form=note_form,
        )
    # post
    if not update_form.validate():
        flash("Error al crear el pedido", "error")
        return render_template(
            "service_requests/service_request-update.html",
            update_form=update_form,
            service_request=service_request,
            note_form=note_form,
        )
    service_request_dbo.update(req_id, status=update_form.data["status"])
    flash("Pedido añadido exitosamente!", "success")
    return redirect(url_for("service_request.service_request_index"))


@service_request_routing.post("/service_requests/<req_id>/notes/create")
@validate_operation(Operations.SERVICE_REQUEST.update)
def service_request_add_note(req_id):
    """
    Add a note to the request
    :param req_id: req id
    """
    note_form = ServiceRequestNoteForm(request.form)
    service_request_dbo.add_note(
        req_id=req_id,
        author_id=session_utils.get_user_id(),
        note=note_form.data["note"],
    )
    flash("Nota añadida exitosamente!", "success")
    return redirect(url_for("service_request.service_request_index"))


@service_request_routing.route("/service_requests/create", methods=["GET", "POST"])
@validate_operation(Operations.SERVICE_REQUEST.create)
def service_request_create():
    """Returns the service_request page"""
    form = ServiceRequestCreateForm(request.form)
    if request.method == "GET":
        form = ServiceRequestCreateForm()
        return render_template(
            "service_requests/service_request-create.html", form=form
        )
    # post
    if not form.validate():
        flash("Error al crear el pedido", "error")
        return render_template(
            "service_requests/service_request-create.html", form=form
        )
    new_service_request = form.data
    new_service_request.pop("csrf_token")
    service_request_dbo.create_new(**new_service_request)
    flash("Pedido añadido exitosamente!", "success")
    return redirect(url_for("service_requests.service_requests_page"))

admin/src/web/templates/service_requests/service_request-index.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% import "_components/pagination.html" as Pagination %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">

    <hgroup class="flex flex-col gap-4 mb-4">

        <div class="flex items-center justify-between">
            <h1 class="text-2xl text-white">Administracion de Pedidos</h1>
            <!-- <a href="{{ url_for('service_request.service_request_create') }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Crear</a> -->
        </div>
        {% call Form.render_form(search_form, method="GET", action=url_for('service_request.service_request_index')) %}
        {{ Form.button_submit("Buscar") }}
        {% endcall %}
    </hgroup>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Titulo
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Usuario
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Tipo de servicio
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Estado
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Fecha de creacion
                    </th>
                    <th scope="col" class="px-3 py-3">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for request in service_requests %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ request.title }}
                    </th>
                    <td class="px-6 py-4">
                        {{ request.user.username }}
                    </td>
                    <td class="px-6 py-4">
                        {{ request.service.service_type.value }}
                    </td>
                    <td class="px-6 py-4">
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                            {{ request.status.value }}</span>
                    </td>
                    <td class="px-6 py-4">
                        {{ request.creation_date.strftime('%d/%m/%Y') }}
                    </td>
                    <td class="px-3 py-4 flex flex-col gap-1">
                        <a href="{{ url_for('service_request.service_request_show', req_id=request.id) }}"  class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Ver</a>
                        <a href="{{ url_for('service_request.service_request_update', req_id=request.id) }}"  class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Editar</a>
                    </td>
                </tr>
                {% endfor %}
                {% if service_requests|length == 0 %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th colspan="10" scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        No se encontraron resultados
                    </th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <br/>
    {{ Pagination.render_pagination(url_for('service_request.service_request_index'), page, total_pages) }}
</section>
</div>
<script src="../path/to/flowbite/dist/flowbite.min.js"></script>
{% endblock %}

admin/src/web/templates/service_requests/service_request-show.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}Informacion pedido{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h2 class="text-2xl text-white mb-4">Informacion del Pedido</h2>
    <section class="mb-12 ">
        <div class="p-4 pt-6 md:mt-4 sm:rounded-lg bg-gray-50">
            <p><strong>Titulo:</strong> {{ service_request.title }}</p>
            <p><strong>Descripcion:</strong> {{ service_request.description }}</p>
            <p><strong>Estado:</strong> {{ service_request.status.value }}</p>
            <p><strong>Usuario del pedido:</strong> {{ service_request.user.username }}</p>
            <p><strong>Nombre de servicio:</strong> {{ service_request.service.name }}</p>
            <p><strong>Fecha de Creacion:</strong> {{ service_request.creation_date }}</p>
            <p><strong>Fecha de Cierre:</strong> {{ service_request.close_date }}</p>
        </div>
    </section>
    <h2 class="text-2xl text-white mb-4">Notas</h2>
    <section class="mb-12 ">
        <ul class="rounded flex flex-col gap-4 overflow-hidden shadow-lg p-4 pt-6 bg-white mt-6">
            {% for note in notes %}
                <div >
                    <p><strong>Nota:</strong> {{ note.note }}</p>
                    <p class="text-sm text-gray-500">Autor: {{ note.author.username }}</p>
                </div>
            {% endfor %}
            {% if service_requests|length == 0 %}
                <div class="bg-white dark:border-gray-700">
                        No se encontraron resultados
                </div>
            {% endif %}
        </ul>
    </section>
    </div>
{% endblock %}

admin/src/web/templates/service_requests/service_request-update.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}Actualizar pedido{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h2 class="text-2xl text-white mb-4">Actualizar Pedido</h2>
    <section class="mb-12">
        {% call Form.render_form(update_form, method="POST", action=url_for('service_request.service_request_update', req_id=service_request.id)) %}
        {{ Form.button_submit("Actualizar") }}
        {% endcall %}
    </section>
    <h2 class="text-2xl text-white mb-4">Agregar Nota</h2>
    <section class="mb-12">
        {% call Form.render_form(note_form, method="POST", action=url_for('service_request.service_request_add_note', req_id=service_request.id)) %}
        {{ Form.button_submit("Actualizar") }}
        {% endcall %}
    </section>
    </div>
{% endblock %}