admin/src/web/utils/forms/institution.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, EmailField, StringField, TextAreaField
from wtforms.validators import DataRequired, Email, Length, Regexp


class InstitutionCreateForm(FlaskForm):
    name = StringField(
        "Nombre",
        validators=[
            DataRequired(),
            Length(max=100, message="Máximo 100 caracteres"),
            Regexp(r"^[a-zA-Z0-9 ]*$", message="Solo letras y números"),
        ],
    )
    address = StringField(
        "Dirección",
        validators=[DataRequired(), Length(max=100, message="Máximo 100 caracteres")],
    )
    location = StringField(
        "Localización",
        validators=[DataRequired(), Length(max=100, message="Máximo 100 caracteres")],
    )
    web = StringField(
        "Web",
        validators=[DataRequired(), Length(max=100, message="Máximo 100 caracteres")],
    )
    days_and_opening_hours = StringField(
        "Cronograma",
        validators=[DataRequired(), Length(max=100, message="Máximo 100 caracteres")],
    )
    information = TextAreaField(
        "Información",
        validators=[DataRequired(), Length(max=1000, message="Máximo 1000 caracteres")],
    )
    keywords = StringField(
        "Palabras clave",
        validators=[
            DataRequired("Campo requerido"),
            Length(max=100, message="Máximo 100 caracteres"),
            Regexp(
                r"^([a-zA-Z0-9]+)(,\s*[a-zA-Z0-9]+)*$",
                message="Solo letras y números separados por coma",
            ),
        ],
    )
    email = EmailField(
        "Correo",
        validators=[
            Email("Correo invalido"),
            DataRequired(),
            Length(max=100, message="Máximo 100 caracteres"),
        ],
    )


class InstitutionUpdateForm(InstitutionCreateForm):
    enabled = BooleanField("Habilitado")


class InstitutionAddOwnerForm(FlaskForm):
    email = EmailField("Correo", validators=[Email("Correo invalido")])

admin/src/web/controllers/institution.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from werkzeug import exceptions

from src.dbo import configuration_dbo, inst_user_role_dbo, institution_dbo
from src.models.enums import Operations, Roles
from src.schemas.institution_schema import index_institution_schema, institution_schema
from src.web.utils.auth import validate_operation
from src.web.utils.forms.crud import ConfirmDeleteForm
from src.web.utils.forms.institution import (
    InstitutionAddOwnerForm,
    InstitutionCreateForm,
    InstitutionUpdateForm,
)

institution_routing = Blueprint(
    "institutions",
    __name__,
    static_folder="static",
    template_folder="templates/institutions",
    url_prefix="/institutions",
)


@institution_routing.get("/")
@validate_operation(Operations.INSTITUTION.index)
def institution_index():
    """Returns all institutions and renders the institution page"""
    q = request.args.get("q", "")
    page = request.args.get("page", 1, type=int)
    per_page = configuration_dbo.get_per_page()
    institutions = institution_dbo.search(q, page, per_page)

    return render_template(
        "institutions/institution-index.html",
        delete_form=ConfirmDeleteForm(),
        institutions=index_institution_schema.dump(institutions),
        page=page,
        total_pages=institutions.pages,
    )


@institution_routing.get("/<inst_id>")
@validate_operation(Operations.INSTITUTION.show)
def institution_show(inst_id):
    """
    Returns the institution page
    :param inst_id: institution id
    """
    current = institution_dbo.get_by_id(inst_id)
    serialized = institution_schema.dump(current)
    serialized["keywords"] = ",".join(serialized["keywords"])
    update_form = InstitutionUpdateForm(data=serialized)
    owner_form = InstitutionAddOwnerForm()
    return render_template(
        "institutions/institution-update.html",
        inst=current,
        update_form=update_form,
        owner_form=owner_form,
    )


@institution_routing.post("/<inst_id>/update")
@validate_operation(Operations.INSTITUTION.update)
def institution_update(inst_id):
    """
    Updates the institution
    :param inst_id: institution id
    """
    current = institution_dbo.get_by_id(inst_id)
    form = InstitutionUpdateForm(request.form)
    if form.validate():
        keywords = form.data["keywords"].split(",")
        keywords = [keyword.strip() for keyword in keywords]
        institution_dbo.update(
            institution=current, data={**form.data, "keywords": keywords}
        )
        flash("Institución actualizada exitosamente!", "success")
    else:
        flash("Error al actualizar la institución", "error")
    return redirect(url_for("institutions.institution_show", inst_id=inst_id))


@institution_routing.post("/<inst_id>/add-owner")
@validate_operation(operation=Operations.INSTITUTION_USER.create)
def add_owner(inst_id):
    """
    Adds a user to an institution as an owner
    :param inst_id: inst id
    """

    form = InstitutionAddOwnerForm(request.form)
    if request.method == "GET":
        form = InstitutionAddOwnerForm()
    elif not form.validate():
        flash("Email invalido", "error")
    elif not inst_user_role_dbo.create_new(
        institution_id=inst_id,
        user_email=form.data.get("email"),
        role=Roles.OWNER.value,
    ):
        flash("No se pudo asignar al usuario", "error")
    else:
        flash("Usuario agregado exitosamente!", "success")
    return redirect(url_for("institutions.institution_show", inst_id=inst_id))


@institution_routing.route("/create", methods=["GET", "POST"])
@validate_operation(Operations.INSTITUTION.create)
def institution_create():
    """Returns the institution create input page"""
    form = InstitutionCreateForm(request.form)
    # Renders the page
    if request.method == "GET":
        form = InstitutionCreateForm()
        return render_template("institutions/institution-create.html", form=form)
    # Handles the form
    if not form.validate():
        flash("Error al crear la institución", "error")
        return render_template("institutions/institution-create.html", form=form)
    new_institution = form.data
    keywords = form.data["keywords"].split(",")
    new_institution["keywords"] = [keyword.strip() for keyword in keywords]
    new_institution.pop("csrf_token")
    try:
        institution_dbo.create_new(**new_institution)
        flash("Institucion añadida exitosamente!", "success")
    except exceptions.HTTPException as exc:
        flash(exc.description, "error")
        return render_template("institutions/institution-create.html", form=form)
    return redirect(url_for("institutions.institution_index"))


@institution_routing.post("/<inst_id>/delete")
@validate_operation(Operations.INSTITUTION.delete)
def institution_delete(inst_id):
    """
    Deletes an institution
    :param inst_id: inst id
    """

    current = institution_dbo.get_by_id(inst_id)
    institution_dbo.delete(current)
    flash("Institutcion eliminada exitosamente!", "success")
    return redirect(url_for("institutions.institution_index"))

admin/src/web/templates/institutions/institution-create.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h1 class="text-2xl text-white mb-4">Crear Institución</h1>
    <section class="mb-12">
        {% call Form.render_form(form, method="POST", action=url_for('institutions.institution_create')) %}
        {{ Form.button_submit("Crear") }}
        {% endcall %}
    </section>
{% endblock %}

admin/src/web/templates/institutions/institution-index.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% import "_components/pagination.html" as Pagination %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl w-7xl mx-auto h-full bg-blue-900 p-6 shadow rounded">
    <hgroup class="flex flex-col gap-4 mb-4">
        <h1 class="text-2xl text-white">Administracion de instituciónes</h1>
        <div class="flex items-center justify-between">
            <form id="search-form" method="GET" action="{{ url_for('institutions.institution_index') }}" class="flex items-center justify-between gap-3">
            <form id="search-form" method="GET" action="{{ url_for('institutions.institution_index') }}" class="flex items-center justify-between gap-3">
                <div class="relative min-w-[16rem]">
                    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500 " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                        </svg>
                    </div>
                    <input type="q" name='q' placeholder="Buscar por palabras clave" class="block w-full p-2 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 " placeholder="Search Mockups, Logos...">
                </div>
                <button type="submit" form="search-form" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 ">Buscar</button>
            </form>
            <a href="{{ url_for('institutions.institution_create') }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 ">Crear</a>
        </div>
    </hgroup>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 ">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nombre
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Correo
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Dirección Completa
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Habilitado
                    </th>
                    <th scope="col" class="px-3 py-3">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for inst in institutions %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        {{ inst.name }}
                    </th>
                    <td class="px-6 py-4">
                        {{ inst.email }}
                    </td>
                    <td class="px-6 py-4">
                        {{ inst.address }}, {{ inst.location }}
                    </td>
                    <td class="px-6 py-4">
                        {% if inst.enabled %}
                        <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                        Si</span>
                        {% else %}
                        <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100">
                        No</span>
                        {% endif %}
                    </td>
                    <td class="px-3 py-4 flex flex-col gap-1">
                        <a href="{{ url_for('institutions.institution_show', inst_id=inst.id) }}" type="submit" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Editar</a>
                        {% call Form.render_form(delete_form, method="POST", action=url_for('institutions.institution_delete', inst_id=inst.id), class='flex') %}
                        {{ Form.button_submit("Eliminar", class="font-medium text-red-600 dark:text-red-500 hover:underline") }}
                        {% endcall %}
                    </td>
                </tr>
                {% endfor %}
                {% if institutions|length == 0 %}
                <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                    <th colspan="10" scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                        No se encontraron resultados
                    </th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <br>
    {{ Pagination.render_pagination(url_for('institutions.institution_index'), page, total_pages) }}
</section>
</div>
{% endblock %}

admin/src/web/templates/institutions/institution-show.html
{% extends "layout.html" %} {% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto bg-blue-900 p-6 shadow">
    <section>
        <hgroup class="flex items-center justify-between">
            <h1 class="text-2xl text-white mb-4">Administracion de instituciónes</h1>
            <button id="open-modal" class="w-20 mb-4 p-2 text-base text-white hover:bg-green-400 hover:text-white rounded text-center" type="button">Agregar</button>
        </hgroup>
        <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                    <tr>
                        <th scope="col" class="px-6 py-3">
                            Nombre
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Información
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Dirección
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Localizacion
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Web
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Palabras Clave
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Cronograma
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Habilitado
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Email
                        </th>
                        <th scope="col" class="px-6 py-3">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for inst in items %}
                    <tr class="bg-white border-b dark:bg-gray-900 dark:border-gray-700">
                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                            {{ inst.name }}
                        </th>
                        <td class="px-6 py-4">
                            {{ inst.information }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.address }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.location }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.web }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.keyword }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.days_and_opening_hours }}
                        </td>
                        <td class="px-6 py-4">
                            {{ inst.email }}
                        </td>
                        <td class="px-6 py-4">
                            {% if inst.True %}
                            <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-full dark:bg-green-700 dark:text-green-100">
                            Si</span>
                            {% else %}
                            <span class="px-2 py-1 font-semibold leading-tight text-red-700 bg-red-100 rounded-full dark:bg-red-700 dark:text-red-100">
                            No</span>
                            {% endif %}
                        </td>
                        <td class="px-6 py-4">
                            <button id="edit-row" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Editar</button>
                        </td>
                    </tr>
                    <tr id="TREdit" class="px-6 py-4 hidden">
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="nombre" type="text" placeholder="Nombre">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="information" type="text" placeholder="Información">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="address" type="text" placeholder="Dirección">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="loc" type="text" placeholder="Localizacion">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="web" type="text" placeholder="Web.com">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="keyword" type="text" placeholder="...">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                            id="days_and_opening_hours" type="text" placeholder="...">
                        </td>
                        <td>
                            <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" type="email" placeholder="Email@mail.com">
                        </td>
                        <td>
                            <input id="enabled" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500
                            dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        </td>
                        <td>
                            <form method="POST" action="#">
                                <button type="submit">Actualizar</button>
                            </form>
                            <a href="#">Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </section>
</div>

<div id="myModal" visi class="flex m-0 modal invisible fixed inset-0 items-center justify-center z-50">
    <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>


    <div class="modal-container bg-white md:mx-auto md:w-96 w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
        <!-- Content -->
        <div class="modal-content py-4 text-left px-6">

            <!-- Formulario CRUD -->
            <form method="POST" action="#">
                <label class="block text-gray-700 text-sm font-bold m-2" for="nombre">
                    Nombre
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="nombre" type="text" placeholder="Nombre">
                <label class="block text-gray-700 text-sm font-bold m-2" for="information">
                    Información
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="information" type="text" placeholder="Información">
                <label class="block text-gray-700 text-sm font-bold m-2" for="address">
                    Dirección
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="address" type="text" placeholder="Dirección">
                <label class="block text-gray-700 text-sm font-bold m-2" for="loc">
                    Localizacion
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="loc" type="text" placeholder="Localizacion">
                <label class="block text-gray-700 text-sm font-bold m-2" for="web">
                    Web
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="web" type="text" placeholder="Web.com">
                <label class="block text-gray-700 text-sm font-bold m-2" for="keyword">
                    Palabras clave
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="keyword" type="text" placeholder="...">
                <label class="block text-gray-700 text-sm font-bold m-2" for="days_and_opening_hours">
                    Cronograma
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 mb-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="days_and_opening_hours" type="text" placeholder="...">
                <br>
                <input id="enabled" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                <label for="enabled" class="ml-2 text-sm font-medium text-gray-900 dark:text-gray-300">Habilitado</label>
                <br>
                <label class="block text-gray-700 text-sm font-bold m-2" for="email">
                    Email
                </label>
                <input class="appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="email" type="email" placeholder="Email@mail.com">

                <!-- Agregar más campos del formulario aquí -->

                <div class="mt-4">
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">
                        Guardar
                    </button>
                    <button id="close-modal" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" type="button">
                        Cerrar
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    //Scripts de Modificación, Agregar y Eliminar

    // MODAL para Agregar
    const openModal = document.getElementById('open-modal');
    const closeModal = document.getElementById('close-modal');
    const modal = document.getElementById('myModal');

    openModal.addEventListener('click', () => {
        modal.classList.remove('invisible');
        modal.classList.add('visible');
    });

    closeModal.addEventListener('click', () => {
        modal.classList.remove('visible');
        modal.classList.add('invisible');
    });


    //DATOS PARA RELLENAR Y PROBAR
    const editRow = document.getElementById('edit-row');
    const row = document.getElementById('TREdit')

    editRow.addEventListener('click', () =>{
        if(row.classList.contains('hidden')){
            row.classList.remove('hidden');
        }
        else{
            row.classList.add('hidden');
        }
    })
</script>
{% endblock %}

admin/src/web/templates/institutions/institution-update.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <section class="flex flex-col gap-6 mb-12">
        <h1 class="text-2xl text-white">Actualizar Institución</h1>
        {% call Form.render_form(update_form, method="POST", action=url_for('institutions.institution_update', inst_id=inst.id)) %}
        {{ Form.button_submit("Actualizar") }}
        {% endcall %}
    </section>
    <section class="flex flex-col gap-6">
        <h1 class="text-2xl text-white">Agregar dueño</h1>
        {% call Form.render_form(owner_form, method="POST", action=url_for('institutions.add_owner', inst_id=inst.id)) %}
        {{ Form.button_submit("Agregar dueño") }}
        {% endcall %}
    </section>
{% endblock %}