admin/src/web/utils/forms/inst_user_role.py
from flask_wtf import FlaskForm
from wtforms import EmailField, SelectField
from wtforms.validators import Email

from src.models.enums import Roles

roles_choices = [
    (Roles.ADMINISTRATOR.value, "Administrador"),
    (Roles.OPERATOR.value, "Operador"),
]


class UserUpdateInstRoleForm(FlaskForm):
    role = SelectField("Rol", choices=roles_choices)


class InstitutionAddUserForm(FlaskForm):
    email = EmailField("Correo", validators=[Email("Correo invalido")])
    role = SelectField("Rol", choices=roles_choices)

admin/src/web/controllers/inst_user_role.py
"""User Institution Role logic"""
from flask import Blueprint, flash, redirect, render_template, request, url_for

from src.dbo import configuration_dbo, inst_user_role_dbo
from src.models.enums import Operations
from src.web.utils import session as session_utils
from src.web.utils.auth import validate_operation
from src.web.utils.forms.crud import ConfirmDeleteForm
from src.web.utils.forms.inst_user_role import (
    InstitutionAddUserForm,
    UserUpdateInstRoleForm,
)

inst_user_role_routing = Blueprint(
    "inst_user_role",
    __name__,
    static_folder="static",
)


@inst_user_role_routing.get("/institution-users")
@validate_operation(Operations.INSTITUTION_USER.index)
def institution_users_page():
    """Returns all users from an institution"""
    inst_id = session_utils.get_inst_id()
    page = request.args.get("page", 1, type=int)
    per_page = configuration_dbo.get_per_page()
    users, total_pages = inst_user_role_dbo.search(
        inst_id, page=page, per_page=per_page
    )

    results = [
        {**user, "role_form": UserUpdateInstRoleForm(role=user["role"])}
        for user in users
    ]
    return render_template(
        "inst-user-roles/institution-users-index.html",
        users=results,
        page=page,
        total_pages=total_pages,
        add_form=InstitutionAddUserForm(),
        delete_form=ConfirmDeleteForm(),
    )


@inst_user_role_routing.route("/inst-user-roles/add-user", methods=["POST", "GET"])
@validate_operation(operation=Operations.INSTITUTION_USER.update)
def create_role():
    """Adds a user to an institution"""
    form = InstitutionAddUserForm(request.form)
    if request.method == "GET":
        form = InstitutionAddUserForm()
        return render_template("inst-user-roles/institution-user-add.html", form=form)
    if not form.validate():
        flash("Email invalido", "error")
        return render_template("inst-user-roles/institution-user-add.html", form=form)
    if not inst_user_role_dbo.create_new(
        session_utils.get_inst_id(), form.data.get("email"), form.data.get("role")
    ):
        flash("El usuario no existe", "error")
        return render_template("inst-user-roles/institution-user-add.html", form=form)
    flash("Usuario agregado exitosamente!", "success")
    return redirect(url_for("inst_user_role.institution_users_page"))


@inst_user_role_routing.post("/inst-user-roles/<user_id>/update-role")
@validate_operation(operation=Operations.INSTITUTION_USER.update)
def update_role(user_id):
    """
    Updates the role in the institution of the user
    :param user_id: user id
    """
    form = UserUpdateInstRoleForm(request.form)
    inst_user_role_dbo.update_role(
        user_id, session_utils.get_inst_id(), form.data.get("role")
    )

    flash("Rol actualizado exitosamente!", "success")
    return redirect(url_for("inst_user_role.institution_users_page"))


@inst_user_role_routing.post("/inst-user-roles/<user_id>/delete-role")
@validate_operation(operation=Operations.INSTITUTION_USER.delete)
def delete_role(user_id):
    """
    Deletes the role of the user in the institution
    :param user_id: user id
    """
    inst_user_role_dbo.delete_role(user_id, session_utils.get_inst_id())
    flash("Usuario eliminado de la institucion!", "success")
    return redirect(url_for("inst_user_role.institution_users_page"))

admin/src/web/templates/inst-user-roles/institution-user-add.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <h1 class="text-2xl text-white mb-4">Agregar a Institución</h1>
    <section class="mb-12">
        {% call Form.render_form(form, method="POST", action=url_for('inst_user_role.create_role')) %}
        {{ Form.button_submit("Agregar") }}
        {% endcall %}
    </section>
{% endblock %}

admin/src/web/templates/inst-user-roles/institution-users-index.html
{% extends "layout.html" %}
{% import "_components/form.html" as Form %}
{% import "_components/pagination.html" as Pagination %}
{% block head %}
{{ super() }} {% endblock %} {% block title %}CRUD{% endblock %}
{% block main %}
<div class="max-w-7xl mx-auto h-full bg-blue-900 p-6 shadow">
    <hgroup class="flex justify-between mb-4">
        <h1 class="text-2xl text-white">Administracion de usuarios de la institucion</h1>
        <div class="flex items-center justify-between">
            <a href="{{ url_for('inst_user_role.create_role') }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 ">Añadir usuario</a>
        </div>
    </hgroup>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left text-gray-500 ">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
                <tr>
                    <th scope="col" class="px-6 py-3">
                        Nombre de usuario
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Nombre completo
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Correo
                    </th>
                    <th scope="col" class="px-6 py-3">
                        Rol
                    </th>
                    <th scope="col" class="px-3 py-3">
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr class="bg-white border-b ">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                        {{ user.username }}
                    </th>
                    <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                        {{ user.firstname }} {{ user.lastname }}
                    </td>
                    <td class="px-6 py-4">
                        {{ user.email }}
                    </td>
                    <td class="px-3 py-4">
                        <form method="POST" id="{{ user.id }}-update" action="{{url_for('inst_user_role.update_role', user_id=user.id)}}" class='flex'>
                        {% call Form.render_field_text(user.role_form.role) %}
                        {% endcall %}
                        </form>
                    </td>
                    <td class="px-3 py-4 flex flex-col gap-1">
                        <div>
                        <button type="submit" form="{{ user.id }}-update" class="font-medium text-blue-600 hover:underline" form="{{ user.id }}-update">Actualizar</button>
                    </div>{% call Form.render_form(delete_form, method="POST", action=url_for('inst_user_role.delete_role', user_id=user.id), class='flex') %}
                        {{ Form.button_submit("Eliminar", class="font-medium text-red-600  hover:underline") }}
                        {% endcall %}
                    </td>
                </tr>
                {% endfor %}
                {% if users|length == 0 %}
                <tr class="bg-white border-b ">
                    <th colspan="10" scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap ">
                        No se encontraron resultados
                    </th>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <br/>
    {{ Pagination.render_pagination(url_for('inst_user_role.institution_users_page'), page, total_pages) }}
</section>
</div>
<script src="../path/to/flowbite/dist/flowbite.min.js"></script>
{% endblock %}